package proyekpbo;

import penjualan.view.barangView;
import penjualan.view.pelangganView1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SMKN 4 BANDUNG
 */
public class MenuBar extends javax.swing.JFrame {

    /**
     * Creates new form MenuBar
     */
    public MenuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        master = new javax.swing.JMenu();
        masterPelanggan = new javax.swing.JMenuItem();
        masterBarang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksiPembelian = new javax.swing.JMenuItem();
        transaksiPenjualan = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporanBarang = new javax.swing.JMenuItem();
        laporanPelanggan = new javax.swing.JMenuItem();
        laporanTransaksi = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home.setMnemonic('f');
        home.setText("HOME");
        jMenuBar1.add(home);

        master.setText("MASTER");

        masterPelanggan.setText("PELANGGAN");
        masterPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterPelangganActionPerformed(evt);
            }
        });
        master.add(masterPelanggan);

        masterBarang.setText("BARANG");
        masterBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterBarangActionPerformed(evt);
            }
        });
        master.add(masterBarang);

        jMenuBar1.add(master);

        transaksi.setText("TRANSAKSI");

        transaksiPembelian.setText("PEMBELIAN");
        transaksi.add(transaksiPembelian);

        transaksiPenjualan.setText("PENJUALAN");
        transaksi.add(transaksiPenjualan);

        jMenuBar1.add(transaksi);

        laporan.setText("LAPORAN");

        laporanBarang.setText("BARANG");
        laporan.add(laporanBarang);

        laporanPelanggan.setText("PELANGGAN");
        laporan.add(laporanPelanggan);

        laporanTransaksi.setText("TRANSAKSI");
        laporan.add(laporanTransaksi);

        jMenuBar1.add(laporan);

        help.setText("HELP");
        jMenuBar1.add(help);

        logout.setText("LOGOUT");
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masterBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterBarangActionPerformed
        // TODO add your handling code here:
        barangView pv = new barangView();
        pv.setLocationRelativeTo(null);
        pv.setVisible(true);
    }//GEN-LAST:event_masterBarangActionPerformed

    private void masterPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterPelangganActionPerformed
        // TODO add your handling code here:
        pelangganView1 bv = new pelangganView1();
        bv.setLocationRelativeTo(null);
        bv.setVisible(true);
    }//GEN-LAST:event_masterPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu help;
    private javax.swing.JMenu home;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporanBarang;
    private javax.swing.JMenuItem laporanPelanggan;
    private javax.swing.JMenuItem laporanTransaksi;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem masterBarang;
    private javax.swing.JMenuItem masterPelanggan;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksiPembelian;
    private javax.swing.JMenuItem transaksiPenjualan;
    // End of variables declaration//GEN-END:variables

}

